### ISSUE TITLE
WARN [RetryUtils] Couldn't connect to the Kubernetes master

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast-kubernetes#139]
Running 1.4 (i can't pull 1.5, not in maven central yet?)

WARN [RetryUtils] Couldn't connect to the Kubernetes master

My k8 master url is correct, RBAC config is good, from inside the container I can hit the k8 master fine. 

This error gives me zero details as to what specifically the issue is. I saw the other change recently that changed the message in https://github.com/hazelcast/hazelcast-kubernetes/pull/133 however even if that was logged it tells me nothing.

Is there an exception that can be logged or further info on the root cause? where should I start looking?

**Comment by bitsofinfo** [comment]
i.e. maybe a flag to give more details like, "i could connect to k8, did a query and got this back" (literal response dumped) etc

**Comment by leszko** [comment]
@bitsofinfo wrt 1.5, it's now marked as "Pre-release". We'll release 1.5 on Wednesday.

After 10 retries, you should see the whole stacktrace with the exact message from the Kubernetes API. So I guess that's what you need. Btw. this number of retries is made configurable (and made default to 3) in 1.5, since we notices 10 retries is a lot and you get the stacktrace too late.
