### ISSUE TITLE
NodePort Service Requires Access to /nodes Kubernetes Resource

### ISSUE THREAD

**Issue by henrikarro** [hazelcast/hazelcast-kubernetes#146]
I'm trying to configure Hazelcast clients outside the Kubernetes cluster where our service is running embedded Hazelcast nodes. We are running in a shared Kubernetes cluster, where we have access only to our own namespaces. We do not have access to LoadBalancer services, so I'm using NodePort services to expose Hazelcast to the clients.

The service account I'm using currently does not have access to the `/nodes` resource. This means that the Hazelcast client connection fails in `KubernetesClient.enrichWithPublicAddresses` when calling `extractNodePublicIp(callGet(nodeUrl))`; the `callGet` method fails with HTTP 403 Forbidden.

I guess someone will say that this is exactly according to design and documentation; the service account should have access to the `/nodes` resource. However, at lesat in our case there is a very simple workaround; we can simply use the node name as public name.

To implement this requires an additional try-catch in `KubernetesClient.enrichWithPublicAddresses`:

    String nodeUrl = String.format("%s/api/v1/nodes/%s", kubernetesMaster, node);
    nodePublicIp = extractNodePublicIp(callGet(nodeUrl));

becomes:

    try {
        String nodeUrl = String.format("%s/api/v1/nodes/%s", kubernetesMaster, node);
        nodePublicIp = extractNodePublicIp(callGet(nodeUrl));
    } catch (Exception e2) {
        LOGGER.warning("Failed to find public IP for node, using node name instead: " + node);
        nodePublicIp = node;
    }

Does anyone see any major problem with this change, or could it added in a future release? Should I in that case create a pull request?

**Comment by hasancelik** [comment]
Hi @henrikarro,

Afaik `node's HostName` is not reachable from outside of the cluster. Could you describe your setup more? How does your external client reach hazelcast cluster via `node's HostName`?

**Comment by googlielmo** [comment]
Hi @henrikarro 

I concur with @hasancelik that it would only be useful when the discovery happens in the same cluster (i.e., not for external clients). That said, I'd be happy to review a PR provided it is optional by some config parameter.

Cheers,
Guglielmo

**Comment by henrikarro** [comment]
I'm currently working with an organization that has set up their own "Kubernetes as a service" solution. In this environment, the node names *are* available outside the cluster and accessible from external clients.  As I'm not a Kubernetes expert, I don't know what the normal behavior is. For testing, I will set up a minikube and see what happens.

If this were to be added as an optional feature, I guess we could add a `useNodeNameInsteadOfExternalIp` boolean parameter; if this is true, we could skip the whole `/nodes` lookup and just use the node name. @googlielmo: is this something like what you had in mind?

**Comment by googlielmo** [comment]
Interesting. And yes, that's what I had in mind.

**Comment by henrikarro** [comment]
OK, I will create a push request, probably during this weekend.

By the way, thank you for creating `hazelcast-kubernetes`, it has proved very useful!

**Comment by mesutcelik** [comment]
I did not know there could be such a use case but true. Some environments are very restrictive and hazelcast-kubernetes is expected to do its best to be compatible with such environments. Thanks for your usecase.

Adding a new flag would normally complicate stuff because you need to be aware of such a flag `useNodeNameInsteadOfExternalIp` and use it in your setup. On the other hand, if we solve it internally by putting some info (not warning) like `Failed to find public IP for node, using node name instead` would be smooth user experience.

We also need to explain this behavior in README and we need to mention that if `nodes` api is restricted then nodes name returned by the api must be reachable through the network.

**Comment by henrikarro** [comment]
OK, I'm open to do it either way; using a flag, or doing it automatically if external IP lookup fails.

So how do you want me to handle this? The benefit of doing it automatically is that it would "just work", a drawback might be that it could lead to strange problems later if the node name is not available from the client.

If we do it automatically, we can log the stack trace of the failed external IP lookup at some finer level, DEBUG or TRACE. That way, you can see exactly what failed if you get the `Failed to find public IP for node, using node name instead`. And maybe we could make the info message more informative, like `Failed to find public IP for node, using node name instead (must be accessible from client)`.

**Comment by googlielmo** [comment]
Yeah in this case doing it automatically should not break compatibility as far as I can see. I agree we should provide informative log messages.

**Comment by mesutcelik** [comment]
Hi @henrikarro ,

Checking it again made me think that using flag is better because that is not a very common use case and if we define the flag in the README very well than people would just pick it up when they need it. It also eliminates the weird cases you described above.

The name should be like `useNodeNameWithExternalClient` but let me know if you find a shorter name.

**Comment by googlielmo** [comment]
Thanks @mesutcelik, I concur. 
@henrikarro looks like we have a plan! Looking forward to your PR.

Cheers,
Guglielmo
