### ISSUE TITLE
Question: on dns resolution

### ISSUE THREAD

**Issue by ramaganapa** [hazelcast/hazelcast-kubernetes#188]
Using DNS lookup with hazelcast 3.12.5 it is not able to resolve DNS unless FQDN is provided
eg: hazelcast-service.my-namespace.svc.local - works but not hazelcast-service.my-namespace.svc

Using the later worked fine with 3.10.5

The reason to leave out kubernetes domain is because we have different kubernetes clusters which don't have same domain name.

Just curious to know if this is expected behavior.

**Comment by leszko** [comment]
Yes, that's the current expected behavior. You can check it here: https://github.com/hazelcast/hazelcast-kubernetes#hazelcast-configuration-1

The reason why it worked before as you mention is that we used a library for the DNS resolution and it probably covered that case. Now, we moved to the zero dependency approach, so we support only FQDN.

If you think, the other DNS service names might be useful, please free to contribute to the hazelcast/hazecast-kubernetes source.

**Comment by ramaganapa** [comment]
Thank you replying. It's good to have but not must have.
