### ISSUE TITLE
narrow the required role

### ISSUE THREAD

**Issue by davidkarlsen** [hazelcast/hazelcast-kubernetes#198]
We run HZ in WLP for session replication, and are looking at running it in embedded mode. Hence there should not be a need for read to pods/endpoints outside of the target namespace - but the client seems to spit out error-messages if it does not get a `clusterrole: view` rolebinding. This seems as a bit wide as a default - especially when running in embedded mode.

Also when logging access errors it simply says error - not what resource and where

**Comment by leszko** [comment]
@davidkarlsen , here's the minimal role you need: https://github.com/helm/charts/blob/master/stable/hazelcast/templates/role.yaml

If you don't use ZONE_AWARE feature, then you can use `Role` instead of `ClusterRole` and you don't need `- nodes` in `resources`.

Btw. let's keep this GH Issue open, because we should update README with these details. You may send a PR if you want.
