### ISSUE TITLE
hybrid hazelcast cluster

### ISSUE THREAD

**Issue by simbatsad** [hazelcast/hazelcast-kubernetes#252]
we want to setup a hazelcast cluster inside kubernetes (embedded) . however another part of the same cluster  should be outside the kubcernetes cluster (embedded in services which are not inside the kubernetes cluster).
is there an option to do so?
what are our options? (we use the community version)

**Comment by leszko** [comment]
I'd suggest keeping Hazelcast cluster either inside or outside Kubernetes. So, if you need Hazelcast members outside Kubernetes cluster, then just use Hazelcast client with the static configuration in your application (instead of embedded Hazelcast).

If you really need to have a Hazelcast cluster, then the option is to use just a static configuration. The members inside Kubernetes cluster should be exposed (with hostPort or some service) and they can form a cluster using public IPs. But TBH we never tried such a configuration.

**Comment by simbatsad** [comment]
@leszko ,thanks, I understand this suggestion (this is our fallback).
but assuming I want to try the full cluster appraoch: If I create a loadbalancer IP per POD instance in kubernetes. then I can put in <members> (inside and outside) these IPs and use TCP discovery? (my fear is that the internal POds will expose their internal addresses using the discovery and also will not identify themselves as members (they have internal IPs)

**Comment by simbatsad** [comment]
another question (related). @leszko , in https://github.com/hazelcast/hazelcast-kubernetes/issues/141 you said that "It will work for server nodes too", this refers to 2 kubernetes clusters but can't it be done in this case somehow?

**Comment by leszko** [comment]
If you use static TCP configuration, then you should use it everywhere. And add an env variable: `JAVA_OPTS="-Dhazelcast.local.publicAddress=<host_ip>:5701". Because the member needs to be aware of its public IP.

If you want to use kubernetes plugin that it may be a little tricky, because you have some members in Kubernetes, some outside. As mentioned, I've never tried such a scenario. You can play with it, maybe it's gonna work.

**Comment by simbatsad** [comment]
thanks we will try it out.
