### ISSUE TITLE
ClassNotFoundException: io.fabric8.kubernetes.client.EditableConfig

### ISSUE THREAD

**Issue by cesartl** [hazelcast/hazelcast-kubernetes#58]
Hi trying to deploy a cluster of Hazelcast in k8s using this library.

My understanding is that I need to build a new Docker image for Hazelcast that contains this jar file and a new config and deploy it in k8s.

So I did the following:

change the `Dockerfile`

```dockerfile
FROM openjdk:8-jre
ENV HZ_VERSION 3.9
...
ADD http://central.maven.org/maven2/com/hazelcast/hazelcast-kubernetes/1.0.0/hazelcast-kubernetes-1.0.0.jar $HZ_HOME
ADD http://central.maven.org/maven2/io/fabric8/kubernetes-client/3.1.0/kubernetes-client-3.1.0.jar $HZ_HOME
ADD hazelcast.xml $HZ_HOME
```

add the jar to the classpath in `server.sh`

```
export CLASSPATH=$HAZELCAST_HOME/hazelcast-kubernetes-1.0.0.jar:$CLASSPATH
export CLASSPATH=$HAZELCAST_HOME/kubernetes-client-3.1.0.jar:$CLASSPATH
```

and use the config `hazelcast.xml`

```xml
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-2.0.xsd"
    xmlns="http://www.hazelcast.com/schema/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <properties>
    </properties>

    <network>
        <join>
            <!-- deactivate normal discovery -->
            <multicast enabled="false"/>
            <tcp-ip enabled="false"/>

            <!-- activate the Kubernetes plugin -->
            <discovery-strategies>
                <discovery-strategy enabled="true"
                                    class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">
                    <properties>
                        <!-- configure discovery service API lookup -->
                        <property name="service-name">${hazelcast.k8s.service}</property>
                        <property name="namespace">${hazelcast.k8s.namespace}</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>
</hazelcast>
```

When the pod start I get the logging message:

```
Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: hazelcast, service-label: null, service-label-value: true, namespace: test, kubernetes-master: https://kubernetes.default.svc}
```

but then just after that I get:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/EditableConfig
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.&lt;init&gt;(HazelcastKubernetesDiscoveryStrategy.java:75)
	at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategyFactory.newDiscoveryStrategy(HazelcastKubernetesDiscoveryStrategyFactory.java:56)
```

What I cannot understand is that `EditableConfig` is an old deprecated class from `kubernetes-client`. I'm using the latest version of the client so I don't understand how the old client would get into the classpath

Am I doing the correct thing here? If so any idea how this exception could happen?

**Comment by googlielmo** [comment]
Hello @cesartl and thanks for asking! 

I assume you are extending the Hazelcast Docker image.
For Kubernetes we recently created a dedicated Docker image, which includes this plugin.
Please take a look at https://github.com/hazelcast/hazelcast-docker/tree/master/hazelcast-kubernetes

Now coming to the particular issue that you are experiencing, I think it's because the `kubernetes-client` v. 3.x dependency was introduced _after_ the 1.0.0 release of this plugin, which depends on the old (v. 1.x) `kubernetes-client`.

By the way, the `hazelcast-kubernetes` Dockerfile uses Maven to download all the transitive dependencies automatically, so you don't have to specify those manually.

At the link above there's also a section on how to provide a custom configuration and additional custom jars by using a Kubernetes persistent volume. You may just as well extend that image to provide customizations, if you prefer.

Hope this helps!

Cheers,
Guglielmo

**Comment by cesartl** [comment]
hi @googlielmo, thanks a lot that's what I was looking for. I will definitely be using that image instead of baking my own.

**Comment by googlielmo** [comment]
You're welcome @cesartl I will update the README for both repos to include this missing piece of information, so thank you for pointing this out!
